name: Deploy to VPS

on:
  push:
    branches:
      - main # Atur di branch apa deploy akan tertrigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/siakad-markaz-v2
            git pull origin main
            sudo docker compose up -d --build
